radiation rework
TenuredCLOUD/Misery pull request #40
Opened 2024-12-30 01:24 UTC by TenuredCLOUD

**When merged this pull request will:**

- shortened and cleaned up some checks with Mike's help

- added radiation zones into marker inArea structure rather than variable / trigger based structure

- fixed classname error for artifact array macro

- removed parseArray function from common - deprecated / useless

- moved the "CBA_settingsInitialized" EH into more components to try and stop debug systemChat spam in main menu

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) from ACE are the expected standard.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-12-30 10:18 UTC, Mike-MF requested changes

2025-01-02 18:16 UTC, TenuredCLOUD commented on addons/gasmask/functions/fnc_useCartridges.sqf
> +    private _artifactStoredStr = format ["<t font='PuristaMedium'>%1</t>", "You replace the cartridges on your gasmask..."];
simple var name change to reflect string name - pulled from inventory component

2025-01-02 19:00 UTC, TenuredCLOUD reviewed
Stuff I missed

2025-01-04 03:03 UTC, Mike-MF approved these changes

2025-01-04 03:03 UTC, merged